### PR TITLE
Add a showcase page.

### LINKED ISSUE #9: Create a Websites Using Gotham page

### PR DESCRIPTION
**Pull request by felicianotech**
Closes #9.

@chayev What do you think of the approach? Also, did I miss anything?

### CODE REVIEW

**Comment by chayev** [comment]
Looks like the theme removes the properties of the <strong> tag. 

I like the approach.

**Review by chayev — APPROVED** [review]

**Comment by felicianotech** [comment]
> Looks like the theme removes the properties of the tag.

What do you mean by this?

**Comment by chayev** [comment]
> What do you mean by this?

Corrected the comment. The strong tag*

**Comment by felicianotech** [comment]
Oh okay. Actually, I should have done that with Markdown anyway. I'll change that.

**Pull request merged**
